=== Envy-rb/xml/data/cand.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/candies" xmlns:tns="http://www.example.com/candies"
        elementFormDefault="qualified">

    <element name="candy" type="tns:CandyType" abstract="true"/>
    <element name="caramel" type="tns:CaramelType" substitutionGroup="tns:candy"/>
    <element name="chocolate" type="tns:ChocolateType" substitutionGroup="tns:candy"/>

    <element name="candies">
        <complexType>
            <sequence>
                <element ref="tns:candy" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="CandyType">
        <sequence>
            <element name="name" type="string"/>
            <element name="proteins" type="tns:Value"/>
            <element name="fats" type="tns:Value"/>
            <element name="carbos" type="tns:Value"/>
            <element name="production" type="tns:Production"/>
            <element name="water" type="tns:Ingredient"/>
            <element name="sugar" type="tns:Ingredient"/>
            <element name="fructose" type="tns:Ingredient"/>
            <element name="vanilla" type="tns:Ingredient"/>
        </sequence>
    </complexType>

    <complexType name="CaramelType">
        <complexContent>
            <extension base="tns:CandyType">
                <sequence>
                    <element name="flavour" type="tns:Flavour"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="ChocolateType">
        <complexContent>
            <extension base="tns:CandyType">
                <sequence>
                    <element name="filling" type="boolean"/>
                    <element name="chocolateKind" type="tns:ChocolateKind"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="ChocolateKind">
        <restriction base="string">
            <enumeration value="black"/>
            <enumeration value="milk"/>
            <enumeration value="white"/>
        </restriction>
    </simpleType>

    <simpleType name="Flavour">
        <restriction base="string">
            <enumeration value="Apple"/>
            <enumeration value="Cherry"/>
            <enumeration value="Orange"/>
        </restriction>
    </simpleType>

    <simpleType name="Ingredient">
        <restriction base="double">
            <minInclusive value="0"/>
            <maxInclusive value="100"/>
        </restriction>
    </simpleType>

    <simpleType name="Value">
        <restriction base="positiveInteger">
            <minInclusive value="0"/>
            <maxInclusive value="999"/>
        </restriction>
    </simpleType>

    <simpleType name="Production">
        <restriction base="string">
            <enumeration value="Europe"/>
            <enumeration value="USA"/>
            <enumeration value="Asia"/>
            <enumeration value="Australia"/>
            <enumeration value="Africa"/>
        </restriction>
    </simpleType>
</schema>

=== Envy-rb/xml/data/cand.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://www.example.com/candies"
              xsi:schemaLocation="http://www.example.com/candies cand.xsd">
    <caramel>
        <name>Caraca</name>
        <proteins>12</proteins>
        <fats>32</fats>
        <carbos>43</carbos>
        <production>Asia</production>
        <water>1</water>
        <sugar>32</sugar>
        <fructose>2</fructose>
        <vanilla>12</vanilla>
        <flavour>Cherry</flavour>
    </caramel>

    <chocolate>
        <name>Choco</name>
        <proteins>32</proteins>
        <fats>34</fats>
        <carbos>54</carbos>
        <production>Africa</production>
        <water>12</water>
        <sugar>43</sugar>
        <fructose>43</fructose>
        <vanilla>1</vanilla>
        <filling>true</filling>
        <chocolateKind>black</chocolateKind>
    </chocolate>

    <chocolate>
        <name>Oco</name>
        <proteins>12</proteins>
        <fats>5</fats>
        <carbos>7</carbos>
        <production>Europe</production>
        <water>7</water>
        <sugar>8</sugar>
        <fructose>9</fructose>
        <vanilla>12</vanilla>
        <filling>false</filling>
        <chocolateKind>white</chocolateKind>
    </chocolate>

    <chocolate>
        <name>Oco</name>
        <proteins>12</proteins>
        <fats>5</fats>
        <carbos>7</carbos>
        <production>Europe</production>
        <water>7</water>
        <sugar>8</sugar>
        <fructose>9</fructose>
        <vanilla>12</vanilla>
        <filling>false</filling>
        <chocolateKind>white</chocolateKind>
    </chocolate>

    <chocolate>
        <name>Oco</name>
        <proteins>12</proteins>
        <fats>5</fats>
        <carbos>7</carbos>
        <production>Europe</production>
        <water>7</water>
        <sugar>8</sugar>
        <fructose>9</fructose>
        <vanilla>12</vanilla>
        <filling>false</filling>
        <chocolateKind>white</chocolateKind>
    </chocolate>

    <chocolate>
        <name>Oco</name>
        <proteins>12</proteins>
        <fats>5</fats>
        <carbos>7</carbos>
        <production>Europe</production>
        <water>7</water>
        <sugar>8</sugar>
        <fructose>9</fructose>
        <vanilla>12</vanilla>
        <filling>false</filling>
        <chocolateKind>white</chocolateKind>
    </chocolate>
</candies>
